# Adapted from https://akhilaariyachandra.com/blog/prettier-in-github-actions

name: Code Quality checks
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true
jobs:
    code-quality:
        name: Code Quality
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                node-version: [18]
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # Fetch all history for all branches and tags

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Run PHP formatting with Pint
              run: npm run format:pint

            - name: Run JS/CSS formatting with Prettier
              run: npm run format:prettier

            - name: Check for changes
              id: git-check
              run: |
                  git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

            - name: Commit changes if any
              if: steps.git-check.outputs.changes == 'true'
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add -A
                  git commit -m "Apply code formatting"
                  git push
